clone:
  depth: 1

definitions:
  steps:
    - step: &node-scripts
        name: Test
        caches:
            - node
        script:
          - npm ci
          - npm run lint --if-present
          - npm run build --if-present
          - npm run test --if-present

pipelines:
  default:
    - parallel:
      - step:
          <<: *node-scripts
          name: Node LTS
          image: node:lts
      - step:
          <<: *node-scripts
          name: Node (latest)
          image: node:latest
