pipelines:
  default:
    - parallel:
      - step:
          name: Node LTS
          image: node:lts
          script:
            - npm install
            - npm run test
      - step:
          name: Node (latest)
          image: node:latest
          script:
            - npm install
            - npm run test
